export const ROLE = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export const PERMISSION = {
	CREATE_USER: "CREATE_USER",
	READ_USER: "READ_USER",
	UPDATE_USER: "UPDATE_USER",
	DELETE_USER: "DELETE_USER",

	CREATE_BRAND: "CREATE_BRAND",
	READ_BRAND: "READ_BRAND",
	UPDATE_BRAND: "UPDATE_BRAND",
	DELETE_BRAND: "DELETE_BRAND",

	CREATE_PRODUCT: "CREATE_PRODUCT",
	READ_PRODUCT: "READ_PRODUCT",
	UPDATE_PRODUCT: "UPDATE_PRODUCT",
	DELETE_PRODUCT: "DELETE_PRODUCT",

	CREATE_ORDER: "CREATE_ORDER",
	READ_ORDER: "READ_ORDER",
	UPDATE_ORDER: "UPDATE_ORDER",
	DELETE_ORDER: "DELETE_ORDER",

	CREATE_CATEGORY: "CREATE_CATEGORY",
	READ_CATEGORY: "READ_CATEGORY",
	UPDATE_CATEGORY: "UPDATE_CATEGORY",
	DELETE_CATEGORY: "DELETE_CATEGORY",
} as const;

type Role = keyof typeof ROLE;

type Permission = keyof typeof PERMISSION;

export const ROLE_PERMISSION: Record<Role, Permission[]> = {
	ADMIN: [
		PERMISSION.CREATE_USER,
		PERMISSION.READ_USER,
		PERMISSION.UPDATE_USER,
		PERMISSION.DELETE_USER,

		PERMISSION.CREATE_BRAND,
		PERMISSION.READ_BRAND,
		PERMISSION.UPDATE_BRAND,
		PERMISSION.DELETE_BRAND,

		PERMISSION.CREATE_PRODUCT,
		PERMISSION.READ_PRODUCT,
		PERMISSION.UPDATE_PRODUCT,
		PERMISSION.DELETE_PRODUCT,

		PERMISSION.CREATE_ORDER,
		PERMISSION.READ_ORDER,
		PERMISSION.UPDATE_ORDER,
		PERMISSION.DELETE_ORDER,

		PERMISSION.CREATE_CATEGORY,
		PERMISSION.READ_CATEGORY,
		PERMISSION.UPDATE_CATEGORY,
		PERMISSION.DELETE_CATEGORY,
	],
	USER: [
		PERMISSION.CREATE_ORDER,
		PERMISSION.READ_ORDER,
		PERMISSION.UPDATE_ORDER,
		PERMISSION.DELETE_ORDER,
	],
};

export type RolePermission = typeof ROLE_PERMISSION;
